/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package top.werls.app.multi.lib.demo.app;

import top.werls.app.multi.lib.demo.list.LinkedList;

import static top.werls.app.multi.lib.demo.utilities.StringUtils.join;
import static top.werls.app.multi.lib.demo.utilities.StringUtils.split;
import static top.werls.app.multi.lib.demo.app.MessageUtils.getMessage;

import org.apache.commons.text.WordUtils;

public class App {
    public static void main(String[] args) {
        LinkedList tokens;
        tokens = split(getMessage());
        String result = join(tokens);
        System.out.println(WordUtils.capitalize(result));
    }
}
