jwt:
  secret: a13yZjSg3CmwvG7F2uav2RgGRBJsd+P8N5H0CrkW5MGdOXTnpYtP/QvaBEh7stJhHZ8EKXxakLe6oV+trB/TYw==
  expiration: 604800
  tokenHead: auth
  interval: 1800
  tokenHeader: Authorization #JWT存储的请求头

spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: 8eaa5c19b29fa2282a21
            clientSecret: 2211b12057efec9ff73b9814b60c5b5a05d10ab0
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:./data.db
  jpa:
    database-platform: org.hibernate.dialect.SQLiteDialect
    hibernate:
      ddl-auto: create