version: '3'
services:
  elasticsearch:
    image: elasticsearch:7.12.0
#    image: elasticsearch:6.8.16
    container_name: elasticsearch
#    mem_limit: 1024m
#    memswap_limit: 512m
    environment:
      - "cluster.name=elasticsearch" #设置集群名称为elasticsearch
      - "discovery.type=single-node" #以单一节点模式启动
      - "bootstrap.memory_lock=true" # 配置内存限制
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m" #设置使用jvm内存大小
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./mydata/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./mydata/elasticsearch/plugins:/usr/share/elasticsearch/plugins #插件文件挂载
#      - ./mydata/elasticsearch/data:/usr/share/elasticsearch/data #数据文件挂载./
    ports:
      - 9200:9200
      - 9300:9300
  logstash:
#    image: logstash:6.8.16
    image: logstash:7.12.0
    container_name: logstash
    environment:
      - TZ=Asia/Shanghai
      - MONITORING_ENABLED:true
      - MONITORING_ELASTICSEARCH.HOSTS:http://es:9200
    volumes:
#      - ./mydata/logstash/logs:/usr/share/logstash/config/logs
      - ./mydata/logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
#      - ./mydata/logstash/logstash.yml:/usr/share/logstash/config/logstash.yml #挂载logstash的配置文件
    depends_on:
      - elasticsearch #kibana在elasticsearch启动之后再启动
    external_links:
      - elasticsearch:es #可以用es这个域名访问elasticsearch 服务
    ports:
      - 4560:4560
      - 4561:4561
      - 4562:4562
      - 4563:4563
  kibana:
    image: kibana:7.12.0
#    image: kibana:6.8.16
    container_name: kibana
    volumes:
      - ./mydata/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    external_links:
      - elasticsearch:es #可以用es这个域名访问elasticsearch服务
    depends_on:
      - elasticsearch #kibana在elasticsearch启动之后再启动
    environment:
      - "i18n.locale='zh-CN'"
      - "elasticsearch.hosts=http://es:9200"
    ports:
      - 5601:5601