version: '3.0'
services:
  mysql_master:
    image: mysql:8.0.29
    container_name: mysql_master
    command:  --default-authentication-plugin=mysql_native_password
    volumes:
      - './mysql/master/data:/var/lib/mysql'

    environment:
      - 'MYSQL_ROOT_PASSWORD=123456'
      - 'TZ: Asia/Shanghai'
    ports:
      - '3306:3306'

  mysql_slave1:
    image: mysql:8.0.29
    container_name: mysql_slave1
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - './mysql/slave1/data:/var/lib/mysql'
    links:
      - 'mysql_master:mysql_master'
    environment:
      - 'MYSQL_ROOT_PASSWORD=123456'
      - 'TZ: Asia/Shanghai'
    ports:
      - '3307:3306'

  mysql_slave2:
    image: mysql:8.0.29
    container_name: mysql_slave2
    command:  --default-authentication-plugin=mysql_native_password

    volumes:
      - './mysql/slave2/data:/var/lib/mysql'
    links:
      - 'mysql_master:mysql_master'
    environment:
      - 'MYSQL_ROOT_PASSWORD=123456'
      - 'TZ: Asia/Shanghai'
    ports:
      - '3308:3306'
