
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://{your mysql ip }:3306/spring_boot_demo?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: demo
    password: demo
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations:
      - classpath:sql
    schemas:
      - spring_boot_demo
    clean-disabled: true