management:
  endpoints:
    jmx:
      exposure:
        include: "*"
    web:
      exposure:
        include: "*"
      base-path: /info
      cors:
        allowed-methods: "*"
        allowed-origins: "*"
