# Using spring-ai-starter-mcp-server-webmvc

spring:
  main:
    banner-mode: off
# Using spring-ai-starter-mcp-server-streamable-webmvc
  ai:
    mcp:
      server:
        protocol: sse
        name: streamable-mcp-server
        version: 1.0.0
        type: SYNC
        instructions: "This streamable server provides real-time notifications"
        resource-change-notification: true
        tool-change-notification: true
        prompt-change-notification: true
management:
  endpoints:
    web:
      exposure:
        include: "*"