/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package top.werls.app.multi.lib.demo.app;

class MessageUtils {
    public static String getMessage() {
        return "Hello      World!";
    }
}
