spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: 8eaa5c19b29fa2282a21
            clientSecret: 2211b12057efec9ff73b9814b60c5b5a05d10ab0
#          authorization:
#            provider: spring
#            client-id: clientId
#            client-secret: $2a$10$KzZZQSWKS0zHnrrBPcaQ7O1pj7HvKMXvM0m..c95l4FfW9GRliopG
#            authorization-grant-type: authorization_code
#            redirect-uri: "http://127.0.0.1:8080/login/oauth2/code/authorization"
#            scope: openid
#            client-name: Auth
#          clientId:
#            provider: spring
#            client-id: clientId
#            client-secret: $2a$10$KzZZQSWKS0zHnrrBPcaQ7O1pj7HvKMXvM0m..c95l4FfW9GRliopG
#            redirect-uri: "http://127.0.0.1:8080/login/oauth2/code/clientId"
##            redirect-uri: "http://127.0.0.1:8080/authorized"
#            scope: read,write
#            client-name: 授权页
#        provider:
#          spring:
#            issuer-uri: http://sample.auth:9000